# Decomposing a Matrix

In [17]:
import numpy as np
A = np.array([[5,4,3],[4,7,2],[3,2,7]])
B = np.array([[10,12],[12,17]])
C= np.array(([1,1],[2,2]))

In [18]:
#A = np.array([[5,4,3],[4,7,2],[3,2,6]])

In [28]:
A

array([[5, 4, 3],
       [4, 7, 2],
       [3, 2, 7]])

In [19]:
np.linalg.det(A)

97.99999999999996

In [20]:
evalA, evec = np.linalg.eig(A)

In [21]:
#eval, evec = np.linalg.eig(C)

In [22]:
evalA

array([12.35987465,  1.5611047 ,  5.07902065])

In [23]:
evec

array([[ 0.56081348,  0.82060437, -0.10998506],
       [ 0.62230189, -0.50540654, -0.59774961],
       [ 0.54610311, -0.26678212,  0.79410245]])

In [29]:
evec[2]@evec[2]

1.0000000000000002

In [30]:
fev = np.array([-0.10998506,-0.59774961,0.79410245])
fev@fev

1.0000000107743583

In [31]:
vec1=np.array(evec[:,0])

In [32]:
vec2 = np.array(evec[:,1])

In [33]:
vec3=np.array(evec[:,2])

In [34]:
mat1 = evalA[0]*np.dot(vec1[:,None],vec1[None,:])
mat1

array([[3.88732586, 4.31353798, 3.78535971],
       [4.31353798, 4.78648062, 4.20039211],
       [3.78535971, 4.20039211, 3.68606817]])

In [35]:
mat2=evalA[1]*np.dot(vec2[:,None],vec2[None,:])
mat2

array([[ 1.05123468, -0.64745071, -0.34176106],
       [-0.64745071,  0.39876197,  0.2104891 ],
       [-0.34176106,  0.2104891 ,  0.11110804]])

In [36]:
mat3=evalA[2]*np.dot(vec3[:,None],vec3[None,:])
mat3

array([[ 0.06143946,  0.33391273, -0.44359864],
       [ 0.33391273,  1.81475741, -2.41088121],
       [-0.44359864, -2.41088121,  3.20282379]])

In [37]:
mat1+mat2+mat3

array([[5., 4., 3.],
       [4., 7., 2.],
       [3., 2., 7.]])